<?php

namespace projetIHM\gestionMairieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HabiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HabiteRepository extends EntityRepository
{
}
