<?php

namespace projetIHM\gestionMairieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MariageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MariageRepository extends EntityRepository
{
}
