parameters:
#    projet_ihm_user.example.class: projetIHM\UserBundle\Example

services:
#    projet_ihm_user.example:
#        class: %projet_ihm_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
