gestion_mairie_homepage:
    pattern: /mairie
    defaults: { _controller: projetIHMgestionMairieBundle:Accueil:index }






gestion_mairie_personne:
    pattern:  /mairie/personne
    defaults: { _controller: projetIHMgestionMairieBundle:Personne:index }

gestion_mairie_personne_xml:
    pattern:  /mairie/personne/rss.xml
    defaults: { _controller: projetIHMgestionMairieBundle:Personne:indexXML }


gestion_mairie_ajouterPersonne:
    pattern:  /mairie/ajouterPersonne
    defaults: { _controller: projetIHMgestionMairieBundle:Personne:ajouterPersonne }

gestion_mairie_supprimerPersonne:
    pattern:  /mairie/supprimerPersonne/{id}
    defaults: { _controller: projetIHMgestionMairieBundle:Personne:supprimerPersonne }
    requirements:
       id:  \d+



gestion_mairie_modifierPersonne:
    pattern:  /mairie/modifierPersonne/{id}
    defaults: { _controller: projetIHMgestionMairieBundle:Personne:modifierPersonne }
    requirements:
       id:  \d+








gestion_mairie_mariage:
    pattern:  /mairie/mariage
    defaults: { _controller: projetIHMgestionMairieBundle:Mariage:index }


gestion_mairie_ajouterMariage:
    pattern:  /mairie/ajouterMariage
    defaults: { _controller: projetIHMgestionMairieBundle:Mariage:ajouterMariage }



gestion_mairie_supprimerMariage:
    pattern:  /mairie/supprimerMariage/{id}
    defaults: { _controller: projetIHMgestionMairieBundle:Mariage:supprimerMariage }









gestion_mairie_logement:
    pattern:  /mairie/logement
    defaults: { _controller: projetIHMgestionMairieBundle:Logement:index }


gestion_mairie_ajouterLogement:
    pattern:  /mairie/ajouterLogement
    defaults: { _controller: projetIHMgestionMairieBundle:Logement:ajouterLogement }


gestion_mairie_modifierLogement:
    pattern:  /mairie/modifierLogement/{id}
    defaults: { _controller: projetIHMgestionMairieBundle:Logement:modifierLogement }






gestion_mairie_habite:
    pattern:  /mairie/habite
    defaults: { _controller: projetIHMgestionMairieBundle:Habite:index }


gestion_mairie_ajouterHabite:
    pattern:  /mairie/ajouterhabite
    defaults: { _controller: projetIHMgestionMairieBundle:Habite:ajouterHabite }

gestion_mairie_supprimerHabite:
    pattern:  /mairie/supprimerHabite/{id}
    defaults: { _controller: projetIHMgestionMairieBundle:Habite:supprimerHabite }
    requirements:
       id:  \d+

