gestion_mairie_homepage:
    pattern:  /mairie
    defaults: { _controller: projetIHMgestionMairieBundle:Accueil:index }

gestion_mairie_personne:
    pattern:  /mairie/personne
    defaults: { _controller: projetIHMgestionMairieBundle:Personne:index }

gestion_mairie_ajouterPersonne:
    pattern:  /mairie/ajouterPersonne
    defaults: { _controller: projetIHMgestionMairieBundle:Personne:ajouterPersonne }

gestion_mairie_supprimerPersonne:
    pattern:  /mairie/supprimerPersonne/{id}
    defaults: { _controller: projetIHMgestionMairieBundle:Personne:supprimerPersonne }
    requirements:
       id:  \d+

gestion_mairie_modifierPersonne:
    pattern:  /mairie/modifierPersonne/{id}
    defaults: { _controller: projetIHMgestionMairieBundle:Personne:modifierPersonne }
    requirements:
       id:  \d+


gestion_mairie_mariage:
    pattern:  /mairie/mariage
    defaults: { _controller: projetIHMgestionMairieBundle:Mariage:index }


gestion_mairie_ajouterMariage:
    pattern:  /mairie/ajouterMariage
    defaults: { _controller: projetIHMgestionMairieBundle:Mariage:ajouterMariage }

